### ISSUE TITLE
[Bug] Some encode can't seek video in Chrome

### ISSUE THREAD

**Issue by okgame** [gpac/mp4box.js#222] opened 2020-12-02 04:03 UTC
Hello
Please check video below.
http://www.mediafire.com/file/zywvmzq6i3eowt4/demo.mp4/file

It play well with basic mp4 method. But got issue with mediasource. Can't seek.
When seek video, player will buff infinity.
If not seek, video play normal.

Play with video tag + mp4 url: All device and browsers.
Play with mediasource: Only work with Firefox, got issue with Chrome.

Info file

> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'demo.mp4':
>   Metadata:
>     major_brand     : mp42
>     minor_version   : 0
>     compatible_brands: isommp42
>     encoder         : Google
>   Duration: 00:44:40.65, start: 0.000000, bitrate: 364 kb/s
>     Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 264 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
>     Metadata:
>       handler_name    : ISO Media file produced by Google Inc.
>     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
>     Metadata:
>       handler_name    : ISO Media file produced by Google Inc.

**Comment by cconcolato** [comment] 2020-12-11 06:26
The file is not fragmented and cannot work as is with MSE. You can fragment it on the fly with mp4box.js following the approach given at https://github.com/gpac/mp4box.js/blob/master/test/index.js which is demonstrated at https://gpac.github.io/mp4box.js/test/index.html. Reopen the issue if this does not work.

**Comment by okgame** [comment] 2020-12-11 10:40
I apologized for not being clear before.
I have test with https://gpac.github.io/mp4box.js/test/index.html in few days before open this issue.

Can you explain more how to make it work with mp4box.js?

**Comment by cconcolato** [comment] 2020-12-11 17:32
I assume you hosted your file on an HTTPS server and used the URL input in https://gpac.github.io/mp4box.js/test/index.html ?

**Comment by okgame** [comment] 2020-12-11 17:44
> I assume you hosted your file on an HTTPS server and used the URL input in https://gpac.github.io/mp4box.js/test/index.html ?

Yes, is this wrong :( ?

**Comment by cconcolato** [comment] 2020-12-11 19:18
No. Is your https server accessible?

**Comment by okgame** [comment] 2020-12-12 03:53
> No. Is your https server accessible?

Hi @cconcolato , sorry for late reply.

Yes. My HTTPS server is accessible!

- I upload demo.mp4 to my hosting at https://mydomain/demo.mp4
- Set header Access-Control-Allow-Origin: * and Accept-Ranges: bytes (img: https://i.imgur.com/OeKMnkU.png )
- Put the url https://mydomain/demo.mp4 to input box URL at https://gpac.github.io/mp4box.js/test/index.html
- Click "Load Media info" (https://i.imgur.com/mrY7BKK.png)
- Click "Play" (img: https://i.imgur.com/OwS3bzZ.png - log: https://anotepad.com/notes/3rewyb2i )

When i seek video in Firefox: It work normal.
When i seek video in Chrome: Video stuck, but still downloading data in background (img: https://i.imgur.com/5cEvSll.png - log: https://anotepad.com/notes/s69prsd5 )

**Comment by cconcolato** [comment] 2020-12-12 05:52
I don't think the problem is related to mp4box.js. It seems to be a problem with the interaction between your server and Chrome. The error messages `Refused to get unsafe header “Content-Range”` are not normal.

**Comment by okgame** [comment] 2020-12-12 06:08
> I don't think the problem is related to mp4box.js. It seems to be a problem with the interaction between your server and Chrome. The error messages `Refused to get unsafe header “Content-Range”` are not normal.

Yes sir, the problem not from mp4box.js

The probem maybe from encode of the file and mediasource.

I have an product use mp4box.js for play video. When i catch this issue, i tracking log of over 100k file, have ~3k file got same issue. Can't seek in Chrome.
90% file got issue have codecs avc1.4d401e

All the file encode by Google Drive. The issue since 1/2019 until now. I don't know how to fix it.


Play file with simple html <video> tag, it work in all browser and device.
Play file with mp4box.js or videostream, it only work with Firefox, not work with Chrome.

Maybe you should test this file from your side. Or test with my https server http://test.vn.center/demo.mp4

**Comment by cconcolato** [comment] 2020-12-12 06:19
From the log the problem does not come from the encode nor from mediasource because it works with Firefox. I think it is an issue with the configuration of the server. You can try things like https://stackoverflow.com/questions/16513131/refused-to-get-unsafe-header-content-range

Since it's not an issue with mp4box.js, I'm closing this issue. Good luck.

**Closed by cconcolato** 2020-12-12 06:19 UTC

**Comment by okgame** [comment] 2020-12-12 07:00
Hi @cconcolato 
Thank you for your advice, it helpful. But it not resolve this issue now.
The error messages Refused to get unsafe header “Content-Range” are not normal. With other video, same server https, it work well. (img: https://i.imgur.com/8DWqoeG.png )
You can test it with my https server at https://test.vn.center/bunny.mp4
That mean, the error messages Refused to get unsafe header “Content-Range” are not reason for seek issue.

I have use same server config for play over 100k video file via mp4box.js. 
Don't know why got issue with some file have codec avc1.4d401e
